_BASE_: "../Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 60
DATASETS:
  TRAIN: ("coco_2017_train_oneshot_s2",)
  TEST: ("coco_2017_val_oneshot_s2",)
TEST:
  EVAL_PERIOD: 5000
